Kamban.Mvc/Models/ErrorViewModel.cs
namespace Kamban.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Kamban.Mvc/Controllers/HomeController.cs
using Kamban.Application.Commands.BitacoraDeTareas;
using Kamban.Application.Commands.Estados;
using Kamban.Application.Commands.Tareas;
using Kamban.Mvc.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace Kamban.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        /// <summary>
        /// Acceso a las reglas de negocio
        /// </summary>
        private readonly IMediator _mediator;

        public HomeController(ILogger<HomeController> logger, IMediator mediator)
        {
            _logger = logger;
            _mediator = mediator;
        }

        public async Task<IActionResult> Index(string estado)
        {
            List<ObtenerTareaCommandResponse> response;
            List<GetEstadosCommandResponse> estados;

            response = await _mediator.Send(new ObtenerTareaCommand { Estado = estado});
            estados = await _mediator.Send(new GetEstadosCommand());
            //estados.Insert(0, new GetEstadosCommandResponse { Id = string.Empty, Nombre = "" });
            ViewBag.Estados = estados.Select(x => new SelectListItem
            {
                Text = x.Nombre,
                Value = x.Nombre
            });

            return View(response);
        }

        public IActionResult AgregarTarea()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AgregarTarea(AgregarTareaCommand command)
        {
            await _mediator.Send(command);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditarTarea(int id)
        {
            ObtenerTareaPorIdCommandResponse response;

            response = await _mediator.Send(new ObtenerTareaPorIdCommand { IdEncodedKey = id.ToString() });
            ViewBag.Estados = (await _mediator.Send(new GetEstadosCommand())).Select(x => new SelectListItem
            {
                Text = x.Nombre,
                Value = x.Nombre
            });

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> EditarTarea(ObtenerTareaCommandResponse commandResponse)
        {
            await _mediator.Send(new ActualizarTareaCommand
            {
                Descripcion = commandResponse.Descripcion,
                Estado = commandResponse.Estado,
                FechaFinal = commandResponse.FechaFinal,
                FechaInicial = commandResponse.FechaInicial,
                Nombre = commandResponse.Nombre,
                TareaIdEncodedKey = commandResponse.Id.ToString(),
                TiempoConsumido = commandResponse.TiempoConsumido,
                TiempoEstimado = commandResponse.TiempoEstimado
            });
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detalles(int id)
        {
            ObtenerTareaPorIdCommandResponse response;

            response = await _mediator.Send(new ObtenerTareaPorIdCommand { IdEncodedKey = id.ToString() });
            ViewData["tareaId"] = id;

            return View(response);
        }

        public IActionResult AgregarBitacora(string tareaId)
        {
            ViewData["tareaId"] = tareaId;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AgregarBitacora(AgregarBitacoraCommand command)
        {
            var data = await _mediator.Send(command);

            return RedirectToAction("Detalles", new { Id = command.TareaIdEncodedKey });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Kamban.Mvc/Controllers/SubtareasController.cs
using Kamban.Application.Commands.Estados;
using Kamban.Application.Commands.Subtareas;
using Kamban.Application.Commands.Tareas;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Kamban.Mvc.Controllers
{
    public class SubtareasController : Controller
    {
        private readonly IMediator _mediator;

        public SubtareasController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public IActionResult Agregar(int tareaId)
        {
            ViewData["tareaId"] = tareaId;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AgregarSubtarea(AgregarSubtareaCommand command)
        {
            var data = await _mediator.Send(command);

            return RedirectToAction("Detalles", "Home", new { Id = command.TareaIdEncodedkey });
        }

        public async Task<IActionResult> Editar(string tareaId, string subtareaId)
        {
            ObtenerTareaPorIdCommandResponse response;
            SubtareaCommand subtarea;

            response = await _mediator.Send(new ObtenerTareaPorIdCommand { IdEncodedKey = tareaId });
            subtarea = response.Subtareas.FirstOrDefault(x => x.EncodedKey == subtareaId);
            ViewData["tareaId"] = tareaId;
            ViewBag.Estados = (await _mediator.Send(new GetEstadosCommand())).Select(x => new SelectListItem
            {
                Text = x.Nombre,
                Value = x.Nombre
            });

            return View(subtarea);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(SubtareaCommand subtarea, string tareaId)
        {
            ActualizarSubtareaCommandResponse response;
            ActualizarSubtareaCommand command;

            command = new ActualizarSubtareaCommand
            {
                Descripcion = subtarea.Descripcion,
                Estado = subtarea.Estado,
                FechaFinal = subtarea.FechaFinal,
                FechaInicial = subtarea.FechaInicial,
                Nombre = subtarea.Nombre,
                SubtareaIdEncodedKey = subtarea.EncodedKey,
                TareaIdEncodedKey = tareaId,
                TiempoConsumido = subtarea.TiempoConsumido,
                TiempoEstimado = subtarea.TiempoEstimado
            };
            response = await _mediator.Send(command);

            return RedirectToAction("Detalles", "Home", new { Id = command.TareaIdEncodedKey });
        }
    }
}

Kamban.Mvc/Views/Home/AgregarBitacora.cshtml
@model Kamban.Application.Commands.BitacoraDeTareas.AgregarBitacoraCommand

@{
    ViewData["Title"] = "Agregar Bitacora";
}

<h1>Agregar Bitacora</h1>

<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="AgregarBitacora">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>            
              
            <input asp-for="TareaIdEncodedKey" type="hidden"  value="@ViewData["tareaId"]" />
            
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

Kamban.Mvc/Views/Home/AgregarSubtareaAsync.cshtml
@model Kamban.Application.Commands.Subtareas.AgregarSubtareaCommand

@{
    ViewData["Title"] = "AgregarSubtareaAsync";
}

<h1>AgregarSubtareaAsync</h1>

<h4>AgregarSubtareaCommand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AgregarSubtareaAsync">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TareaIdEncodedkey" class="control-label"></label>
                <input asp-for="TareaIdEncodedkey" class="form-control" />
                <span asp-validation-for="TareaIdEncodedkey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EncodedKey" class="control-label"></label>
                <input asp-for="EncodedKey" class="form-control" />
                <span asp-validation-for="EncodedKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicial" class="control-label"></label>
                <input asp-for="FechaInicial" class="form-control" />
                <span asp-validation-for="FechaInicial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFinal" class="control-label"></label>
                <input asp-for="FechaFinal" class="form-control" />
                <span asp-validation-for="FechaFinal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiempoEstimado" class="control-label"></label>
                <input asp-for="TiempoEstimado" class="form-control" />
                <span asp-validation-for="TiempoEstimado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiempoConsumido" class="control-label"></label>
                <input asp-for="TiempoConsumido" class="form-control" />
                <span asp-validation-for="TiempoConsumido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Kamban.Mvc/Views/Home/AgregarTarea.cshtml
@model Kamban.Application.Commands.Tareas.AgregarTareaCommand

@{
    ViewData["Title"] = "AgregarTarea";
}

<h1>Agregar Tarea</h1>

<hr />
<div class="row">
    <div class="col-md-5">
        <form asp-action="AgregarTarea">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>            
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicial" class="control-label"></label>
                <input asp-for="FechaInicial" class="form-control" />
                <span asp-validation-for="FechaInicial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFinal" class="control-label"></label>
                <input asp-for="FechaFinal" class="form-control" />
                <span asp-validation-for="FechaFinal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiempoEstimado" class="control-label"></label>
                <input asp-for="TiempoEstimado" class="form-control" />
                <span asp-validation-for="TiempoEstimado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiempoConsumido" class="control-label"></label>
                <input asp-for="TiempoConsumido" class="form-control" />
                <span asp-validation-for="TiempoConsumido" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Kamban.Mvc/Views/Home/Detalles.cshtml
@model Kamban.Application.Commands.Tareas.ObtenerTareaPorIdCommandResponse

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>    
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EncodedKey)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EncodedKey)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicial)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaInicial)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFinal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaFinal)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeRegistro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaDeRegistro)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TiempoEstimado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TiempoEstimado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TiempoConsumido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TiempoConsumido)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bitacora)
        </dt>
        <dd class="col-sm-10">
            @await Html.PartialAsync("_Bitacoras", Model.Bitacora.OrderByDescending(x => x.FechaDeRegistro))
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Subtareas)
        </dt>
        <dd class="col-sm-10">
            @await Html.PartialAsync("_Subtareas", Model.Subtareas.OrderByDescending(x => x.Estado))
        </dd>
    </dl>

</div>
<div>
    @* @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) | *@
    <a asp-action="Index">Regresar a la lista</a>
</div>

Kamban.Mvc/Views/Home/EditarTarea.cshtml
@model Kamban.Application.Commands.Tareas.ObtenerTareaPorIdCommandResponse

@{
    ViewData["Title"] = "Editar Tarea";
}

<h1>Editar Tarea</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarTarea">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="Id" type="hidden" />

            <div class="form-group">
                <label asp-for="EncodedKey" class="control-label"></label>
                <input asp-for="EncodedKey" class="form-control" />
                <span asp-validation-for="EncodedKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-select"  asp-items="ViewBag.Estados"></select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicial" class="control-label"></label>
                <input asp-for="FechaInicial" class="form-control" />
                <span asp-validation-for="FechaInicial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFinal" class="control-label"></label>
                <input asp-for="FechaFinal" class="form-control" />
                <span asp-validation-for="FechaFinal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDeRegistro" class="control-label"></label>
                <input asp-for="FechaDeRegistro" class="form-control"  disabled/>
                <span asp-validation-for="FechaDeRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiempoEstimado" class="control-label"></label>
                <input asp-for="TiempoEstimado" class="form-control" />
                <span asp-validation-for="TiempoEstimado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiempoConsumido" class="control-label"></label>
                <input asp-for="TiempoConsumido" class="form-control" />
                <span asp-validation-for="TiempoConsumido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Kamban.Mvc/Views/Home/Index.cshtml
@model IEnumerable<Kamban.Application.Commands.Tareas.ObtenerTareaCommandResponse>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de tareas</h1>

<p>
    <a asp-action="AgregarTarea">Agregar tareas</a>
</p>
<div>
    <label class="form-label"></label>
    <select class="form-select" asp-items="ViewBag.Estados" onchange="filtrar()" id="selectEstado">
        <option value="">Todos</option>
    </select>
</div>
<table class="table">
    <thead>
        <tr>
            @* <th>
            @Html.DisplayNameFor(model => model.Id)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            @*   <th>
            @Html.DisplayNameFor(model => model.FechaInicial)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.FechaFinal)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.FechaDeRegistro)
            </th>
            @*  <th>
            @Html.DisplayNameFor(model => model.TiempoEstimado)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.TiempoConsumido)
            </th> *@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @* <td>
            @Html.DisplayFor(modelItem => item.Id)
            </td> *@
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                @*  <td>
            @Html.DisplayFor(modelItem => item.FechaInicial)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.FechaFinal)
            </td> *@
                <td>
                    @Html.DisplayFor(modelItem => item.FechaDeRegistro)
                </td>
                @*  <td>
            @Html.DisplayFor(modelItem => item.TiempoEstimado)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.TiempoConsumido)
            </td> *@
                <td>
                    <a href="/Home/AgregarBitacora?tareaId=@item.Id">Agregar Bitacora</a> |
                    <a href="/Home/EditarTarea/@item.Id">Editar</a> |
                    @* <a href="/Home/EditarTarea/@item.Id">Finalizar</a>  |
                <a href="/Home/EditarTarea/@item.Id">Pausa</a>  |  *@
                    @Html.ActionLink("Detalles", "Detalles", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script>
        function filtrar() {
            let estado = document.getElementById('selectEstado').value
            window.location.href = "/?estado=" + estado
        }

        function seleccionarEstado() {
            let params = new URLSearchParams(window.location.search);
            let estado = params.get('estado'); // 'John'
            console.log(estado)
            if (estado == null)
                document.getElementById('selectEstado').value = ""
            else
                document.getElementById('selectEstado').value = estado
        }

        window.addEventListener('load', (event) => {
            console.log('The page has fully loaded');
            seleccionarEstado()
        });
    </script>
}

Kamban.Mvc/Views/Home/_Bitacoras.cshtml
@model IEnumerable<Kamban.Domain.Entities.Bitacora>

<p>
    <a asp-action="AgregarBitacora" asp-route-tareaId="@ViewData["tareaId"]">Agregar bitacora</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDeRegistro)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaDeRegistro)
                </td>
            </tr>
        }
    </tbody>
</table>

Kamban.Mvc/Views/Home/_Subtareas.cshtml
@model IEnumerable<Kamban.Application.Commands.Tareas.SubtareaCommand>

<p>
    <a asp-action="Agregar" asp-controller="Subtareas" asp-route-tareaId="@ViewData["tareaId"]">Agregar subtarea</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInicial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaFinal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TiempoEstimado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TiempoConsumido)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaInicial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaFinal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TiempoEstimado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TiempoConsumido)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", "Subtareas", new { tareaId = ViewData["tareaId"], subtareaId = item.EncodedKey }) 
                    @* @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) | *@
                    @* @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }) *@
                </td>
            </tr>
        }
    </tbody>
</table>

Kamban.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kamban.Mvc</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Kamban.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kamban.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Kamban.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>